---
- name: Example Playbook to install AWS CLI
  hosts: all
  become: yes

  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install unzip
      ansible.builtin.apt:
        name: unzip
        state: present

    - name: Download AWS CLI v2 installer
      ansible.builtin.get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Unzip AWS CLI
      ansible.builtin.unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp/
        remote_src: yes

    - name: Install AWS CLI
      ansible.builtin.command: /tmp/aws/install
      args:
        creates: /usr/local/bin/aws

    - name: Verify AWS CLI version
      ansible.builtin.command: aws --version
